import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header/"
import Presentation from '../components/Presentation'
import Main from '../components/Main'
import Footer from '../components/Footer'

export default function Home () {
  return (
    <div>
      <Head>
        <title>PetCare - Todo cuidado para seu bichinho </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <Header />
        <Presentation />
        <Main />
        <Footer />
      </div>
    </div>
  )
}
